"""added a limit to number questions asked

Revision ID: 01ac23292b45
Revises: 49776fe96e42
Create Date: 2019-09-12 20:49:33.889570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ac23292b45'
down_revision = '49776fe96e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('no_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'no_questions')
    # ### end Alembic commands ###
