"""lesson types

Revision ID: 26fb10d9e2f9
Revises: e943deea93f0
Create Date: 2018-12-19 20:11:27.067150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fb10d9e2f9'
down_revision = 'e943deea93f0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessontypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'lessontypes', ['type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'type_id')
    op.drop_table('lessontypes')
    ### end Alembic commands ###
