"""Qs are now linked to skills

Revision ID: 3248faee0a72
Revises: db38394a1bc9
Create Date: 2019-11-03 17:17:34.041638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3248faee0a72'
down_revision = 'db38394a1bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_ibfk_2', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'skills', ['skill_id'], ['id'])
    op.drop_column('questions', 'quiz_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('quiz_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_ibfk_2', 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('questions', 'skill_id')
    # ### end Alembic commands ###
