"""renamed announcements from posts to announcements

Revision ID: 45d3e7ef7f38
Revises: 3248faee0a72
Create Date: 2019-11-23 18:50:50.949529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45d3e7ef7f38'
down_revision = '3248faee0a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_html', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_date_posted'), 'announcements', ['date_posted'], unique=False)
    op.create_table('announcement_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_index('ix_posts_date_posted', table_name='posts')
    op.drop_table('posts')
    op.drop_table('post_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_tags_ibfk_2'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='post_tags_ibfk_1'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('body_html', mysql.TEXT(), nullable=True),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('summary_html', mysql.TEXT(), nullable=True),
    sa.Column('date_posted', mysql.DATETIME(), nullable=True),
    sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='posts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_posts_date_posted', 'posts', ['date_posted'], unique=False)
    op.drop_table('announcement_tags')
    op.drop_index(op.f('ix_announcements_date_posted'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
