"""added problem_id field to problemmistakes

Revision ID: 49776fe96e42
Revises: 6cf8737fda65
Create Date: 2019-08-24 21:05:28.818724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49776fe96e42'
down_revision = '6cf8737fda65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemmistakes', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.add_column('problemmistakes', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problemmistakes', 'questions', ['question_id'], ['id'])
    op.drop_column('problemmistakes', 'is_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemmistakes', sa.Column('is_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problemmistakes', type_='foreignkey')
    op.drop_column('problemmistakes', 'question_id')
    op.drop_column('problemmistakes', 'is_closed')
    # ### end Alembic commands ###
