"""teacher extra content

Revision ID: 4ed1baba2b11
Revises: d46f78108b33
Create Date: 2019-11-30 16:57:59.781277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed1baba2b11'
down_revision = 'd46f78108b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachernotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachernotes_date_posted'), 'teachernotes', ['date_posted'], unique=False)
    op.create_index(op.f('ix_teachernotes_last_updated'), 'teachernotes', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachernotes_last_updated'), table_name='teachernotes')
    op.drop_index(op.f('ix_teachernotes_date_posted'), table_name='teachernotes')
    op.drop_table('teachernotes')
    # ### end Alembic commands ###
