"""strand to module

Revision ID: 601b0d44f146
Revises: f04a439cf6a4
Create Date: 2018-09-29 13:43:42.410933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '601b0d44f146'
down_revision = 'f04a439cf6a4'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_module_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('strand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chapters', sa.Column('module_id', sa.Integer(), nullable=True))
    op.drop_constraint('chapters_ibfk_2', 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'modules', ['module_id'], ['id'])
    op.drop_column('chapters', 'strand_id')
    op.drop_table('strands')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('strand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key('chapters_ibfk_2', 'chapters', 'strands', ['strand_id'], ['id'])
    op.drop_column('chapters', 'module_id')
    op.create_table('strands',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('next_strand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('strand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['next_strand_id'], ['strands.id'], name='strands_ibfk_1'),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], name='strands_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('modules')
    ### end Alembic commands ###
