"""added is_open field to problemmistakes

Revision ID: 6cf8737fda65
Revises: 70ea916ed61b
Create Date: 2019-08-24 20:06:05.178944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf8737fda65'
down_revision = '70ea916ed61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemmistakes', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problemmistakes', 'is_open')
    # ### end Alembic commands ###
