"""reporting mistakes in problems

Revision ID: 70ea916ed61b
Revises: 74f4a4efde41
Create Date: 2019-08-18 20:37:39.880707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ea916ed61b'
down_revision = '74f4a4efde41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemmistaketypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mistake_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemmistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('problem_mistake_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_mistake_type_id'], ['problemmistaketypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problemmistakes')
    op.drop_table('problemmistaketypes')
    # ### end Alembic commands ###
