"""empty message

Revision ID: 71505bb01ff3
Revises: a6fb11de7989
Create Date: 2018-10-30 13:25:46.270571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71505bb01ff3'
down_revision = 'a6fb11de7989'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'active')
    ### end Alembic commands ###
