"""added datetime to studentassignments table

Revision ID: 74f4a4efde41
Revises: 393dcaabbc3c
Create Date: 2019-07-26 15:56:31.408687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74f4a4efde41'
down_revision = '393dcaabbc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_column('assignments', 'due_time')
    op.add_column('student_assignments', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_assignments', 'datetime')
    op.add_column('assignments', sa.Column('due_time', mysql.DATETIME(), nullable=True))
    op.drop_column('assignments', 'due_date')
    # ### end Alembic commands ###
