"""removed explanation field from question

Revision ID: 7f0e2d3605d4
Revises: d068c561fadb
Create Date: 2019-06-01 14:41:30.829567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f0e2d3605d4'
down_revision = 'd068c561fadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'solution')
    op.drop_column('questions', 'solution_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('solution_html', mysql.TEXT(), nullable=True))
    op.add_column('questions', sa.Column('solution', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
