"""empty message

Revision ID: 9557d8dae753
Revises: a150d2ea9d31
Create Date: 2019-03-30 15:10:59.110252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9557d8dae753'
down_revision = 'a150d2ea9d31'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('hint_no', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hints')
    ### end Alembic commands ###
