"""quiz types

Revision ID: 97e77c2292ff
Revises: f2efa862ced7
Create Date: 2018-12-08 13:49:48.805293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e77c2292ff'
down_revision = 'f2efa862ced7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiztypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quizzes', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'quiztypes', ['type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'type_id')
    op.drop_table('quiztypes')
    ### end Alembic commands ###
