"""empty message

Revision ID: a150d2ea9d31
Revises: b71157b7c81f
Create Date: 2019-01-19 13:44:19.917702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a150d2ea9d31'
down_revision = 'b71157b7c81f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('solution', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('solution_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'solution_html')
    op.drop_column('questions', 'solution')
    ### end Alembic commands ###
