"""topic to strand

Revision ID: a6fb11de7989
Revises: 601b0d44f146
Create Date: 2018-09-29 13:55:41.521733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6fb11de7989'
down_revision = '601b0d44f146'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('modules', sa.Column('strand_id', sa.Integer(), nullable=True))
    op.drop_constraint('modules_ibfk_2', 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'strands', ['strand_id'], ['id'])
    op.drop_column('modules', 'topic_id')
    op.drop_table('topics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key('modules_ibfk_2', 'modules', 'topics', ['topic_id'], ['id'])
    op.drop_column('modules', 'strand_id')
    op.create_table('topics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('strands')
    ### end Alembic commands ###
