"""linked quiz with skills

Revision ID: b71157b7c81f
Revises: 26fb10d9e2f9
Create Date: 2018-12-22 16:38:57.952555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71157b7c81f'
down_revision = '26fb10d9e2f9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_skills',
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_skills')
    ### end Alembic commands ###
