"""added datetime to quizattempts table

Revision ID: d068c561fadb
Revises: 3184d81e4a07
Create Date: 2019-05-11 15:21:37.784104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd068c561fadb'
down_revision = '3184d81e4a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizattempts', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizattempts', 'datetime')
    # ### end Alembic commands ###
