"""comments table for teacher blog

Revision ID: d46f78108b33
Revises: 16b5f8a638f8
Create Date: 2019-11-30 13:25:35.830532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46f78108b33'
down_revision = '16b5f8a638f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postcomments_date_posted'), 'postcomments', ['date_posted'], unique=False)
    op.add_column('posts', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_last_updated'), 'posts', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_last_updated'), table_name='posts')
    op.drop_column('posts', 'last_updated')
    op.drop_index(op.f('ix_postcomments_date_posted'), table_name='postcomments')
    op.drop_table('postcomments')
    # ### end Alembic commands ###
