"""Added score to UserAnswer table

Revision ID: d94d38c6a0e2
Revises: 9557d8dae753
Create Date: 2019-04-06 14:05:58.824832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94d38c6a0e2'
down_revision = '9557d8dae753'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useranswers', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useranswers', 'score')
    ### end Alembic commands ###
