"""added fields to chapter table

Revision ID: db38394a1bc9
Revises: 01ac23292b45
Create Date: 2019-10-29 12:30:25.714770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db38394a1bc9'
down_revision = '01ac23292b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('chapters', sa.Column('name', sa.Text(), nullable=True))
    op.drop_column('chapters', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('icon', mysql.TEXT(), nullable=True))
    op.drop_column('chapters', 'name')
    op.drop_column('chapters', 'image_url')
    # ### end Alembic commands ###
