"""empty message

Revision ID: e943deea93f0
Revises: 97e77c2292ff
Create Date: 2018-12-08 15:29:23.954841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e943deea93f0'
down_revision = '97e77c2292ff'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('learningoutcomes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learningoutcomes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('lesson_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='learningoutcomes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('skills')
    ### end Alembic commands ###
