"""change module to chapter

Revision ID: f04a439cf6a4
Revises: 6632c94f4ed8
Create Date: 2018-09-29 10:24:25.546901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f04a439cf6a4'
down_revision = '6632c94f4ed8'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('next_chapter_id', sa.Integer(), nullable=True),
    sa.Column('strand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.drop_constraint('lessons_ibfk_1', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('lessons', 'module_id')
    op.drop_table('modules')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_ibfk_1', 'lessons', 'modules', ['module_id'], ['id'])
    op.drop_column('lessons', 'chapter_id')
    op.create_table('modules',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('icon', mysql.TEXT(), nullable=True),
    sa.Column('next_module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('strand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['next_module_id'], ['modules.id'], name='modules_ibfk_1'),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], name='modules_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('chapters')
    ### end Alembic commands ###
