"""empty message

Revision ID: f2efa862ced7
Revises: 71505bb01ff3
Create Date: 2018-12-08 13:29:55.135668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2efa862ced7'
down_revision = '71505bb01ff3'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('next_quiz_id', sa.Integer(), nullable=True))
    op.drop_constraint('quizzes_ibfk_1', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'quizzes', 'quizzes', ['next_quiz_id'], ['id'])
    op.drop_column('quizzes', 'page_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_ibfk_1', 'quizzes', 'pages', ['page_id'], ['id'])
    op.drop_column('quizzes', 'next_quiz_id')
    op.drop_column('quizzes', 'lesson_id')
    ### end Alembic commands ###
